In [1]:
import pandas as pd

# Chemin vers le fichier CSV
csv_file = 'E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo_modifié.csv'

# Lire le fichier CSV
try:
    df = pd.read_csv(csv_file, encoding='utf-8', sep=',')
    print(df.head())  # Afficher les premières lignes du DataFrame
except Exception as e:
    print(f"Une erreur s'est produite lors de la lecture du fichier : {e}")

Une erreur s'est produite lors de la lecture du fichier : 'utf-8' codec can't decode byte 0xc2 in position 12: invalid continuation byte

In [8]:
import pandas as pd
df_train = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv') # load the .csv file, specify the appropriate path
utt = df_train['Utterance'].tolist() # load the list of utterances
dia_id = df_train['Dialogue_ID'].tolist() # load the list of dialogue id's
utt_id = df_train['Utterance_ID'].tolist() # load the list of utterance id's
for i in range(len(utt)):
    print ('Utterance: ' + utt[i]) # display utterance
    print ('Video Path: train_splits/dia' + str(dia_id[i]) + '_utt' + str(utt_id[i]) + '.mp4') # display the video file path
    print ()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 972: invalid continuation byte

In [38]:
import pandas as pd
import csv  # Importer le module csv

# Charger le fichier CSV avec des paramètres ajustés
df = pd.read_csv(
    'E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv',
    sep=",",                  # Délimiteur (virgule)
    encoding='ISO-8859-1',   # Encodage
    quotechar='"',            # Caractère de citation
    quoting=csv.QUOTE_ALL,    # Citer tous les champs
    skipinitialspace=True,    # Ignorer les espaces après les virgules
    on_bad_lines='skip'       # Ignorer les lignes incorrectes
)

# Afficher les premières lignes du DataFrame
print("Données originales :")
print(df.head())

# Convertir la colonne 'Utterance' en chaînes, en remplaçant les NaN par des chaînes vides
df['Utterance'] = df['Utterance'].astype(str).str.replace('Â', '', regex=False)
df['Utterance'] = df['Utterance'].str.replace('', "'", regex=False)  # Remplacer les caractères indésirables

# Vérifier les noms de colonnes
print("\nNoms des colonnes :")
print(df.columns)

# Afficher les données nettoyées
print("\nDonnées nettoyées :")
print(df.head())

# Enregistrer le fichier nettoyé
df.to_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo_cleaned22.csv', index=False, encoding='ISO-8859-1')

print("\nFichier nettoyé enregistré avec succès.")

Données originales :
                                              Sr No.  Utterance  Speaker  \
0  1,"also I was the point person on my companyÂ...        NaN      NaN
1  2,"You mustÂve had your hands full.",The Inte...        NaN      NaN
2  3,"That I did. That I did.",Chandler,neutral,n...        NaN      NaN
3  4,"So letÂs talk a little bit about your duti...        NaN      NaN
4  5,"My duties?  All right.",Chandler,surprise,p...        NaN      NaN

   Emotion  Sentiment  Dialogue_ID  Utterance_ID  Season  Episode  StartTime  \
0      NaN        NaN          NaN           NaN     NaN      NaN        NaN
1      NaN        NaN          NaN           NaN     NaN      NaN        NaN
2      NaN        NaN          NaN           NaN     NaN      NaN        NaN
3      NaN        NaN          NaN           NaN     NaN      NaN        NaN
4      NaN        NaN          NaN           NaN     NaN      NaN        NaN

   EndTime
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

Noms des colonnes :
Index(['Sr No.', 'Utterance', 'Speaker', 'Emotion', 'Sentiment', 'Dialogue_ID',
       'Utterance_ID', 'Season', 'Episode', 'StartTime', 'EndTime'],
      dtype='object')

Données nettoyées :
                                              Sr No. Utterance  Speaker  \
0  1,"also I was the point person on my companyÂ...       nan      NaN
1  2,"You mustÂve had your hands full.",The Inte...       nan      NaN
2  3,"That I did. That I did.",Chandler,neutral,n...       nan      NaN
3  4,"So letÂs talk a little bit about your duti...       nan      NaN
4  5,"My duties?  All right.",Chandler,surprise,p...       nan      NaN

   Emotion  Sentiment  Dialogue_ID  Utterance_ID  Season  Episode  StartTime  \
0      NaN        NaN          NaN           NaN     NaN      NaN        NaN
1      NaN        NaN          NaN           NaN     NaN      NaN        NaN
2      NaN        NaN          NaN           NaN     NaN      NaN        NaN
3      NaN        NaN          NaN           NaN     NaN      NaN        NaN
4      NaN        NaN          NaN           NaN     NaN      NaN        NaN

   EndTime
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

Fichier nettoyé enregistré avec succès.

In [39]:
df

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,"1,""also I was the point person on my companyÂ...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"2,""You mustÂve had your hands full."",The Inte...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"3,""That I did. That I did."",Chandler,neutral,n...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"4,""So letÂs talk a little bit about your duti...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"5,""My duties? All right."",Chandler,surprise,p...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
150,"154,""Joey is a great guy, but we're just... so...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,"155,""I knew that was him!"",Ross,anger,negative...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,"156,""Anyway I just, uh, I think it's for the b...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,"157,""Hey, you ok?"",Ross,neutral,neutral,15,8,9...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,"158,""I guess."",Charlie,sadness,negative,15,9,9...",nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import pandas as pd
import chardet

# Detect encoding
with open('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']
    print(f"Detected encoding: {encoding}")

# Load the CSV file with the detected encoding
df = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv', encoding=encoding, sep=",", quotechar='"')

# Display the first few rows
print(df.head())

Detected encoding: Windows-1252
                                              Sr No.  Utterance  Speaker  \
0  1,"also I was the point person on my companyÂ’...        NaN      NaN
1  2,"You mustÂ’ve had your hands full.",The Inte...        NaN      NaN
2  3,"That I did. That I did.",Chandler,neutral,n...        NaN      NaN
3  4,"So letÂ’s talk a little bit about your duti...        NaN      NaN
4  5,"My duties?  All right.",Chandler,surprise,p...        NaN      NaN

   Emotion  Sentiment  Dialogue_ID  Utterance_ID  Season  Episode  StartTime  \
0      NaN        NaN          NaN           NaN     NaN      NaN        NaN
1      NaN        NaN          NaN           NaN     NaN      NaN        NaN
2      NaN        NaN          NaN           NaN     NaN      NaN        NaN
3      NaN        NaN          NaN           NaN     NaN      NaN        NaN
4      NaN        NaN          NaN           NaN     NaN      NaN        NaN

   EndTime
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

In [18]:
import pandas as pd
import chardet

# Detect encoding
with open('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv', 'rb') as f:
    result = chardet.detect(f.read())
    encoding = result['encoding']
    print(f"Detected encoding: {encoding}")

# Load the CSV file with refined parameters
try:
    df = pd.read_csv(
        'path_to_your_file.csv',
        encoding=encoding,        # Detected encoding
        sep=",",                  # Separator (comma for CSV)
        quotechar='"',            # Character used for quoting
        quoting=pd.io.common.QUOTE_MINIMAL,  # Adjust quoting
        skipinitialspace=True,    # Skip spaces after the delimiter
        error_bad_lines=False,    # Skip bad lines
        warn_bad_lines=True       # Show warnings for bad lines
    )
except Exception as e:
    print(f"Error reading the CSV file: {e}")

# Display the first few rows of the DataFrame
print(df.head())

# Optional: Clean up the 'Utterance' column to fix special characters
df['Utterance'] = df['Utterance'].str.replace('Â', '', regex=False)

# Display the cleaned DataFrame
print(df.head())

Detected encoding: Windows-1252
Error reading the CSV file: module 'pandas.io.common' has no attribute 'QUOTE_MINIMAL'
                                              Sr No.  Utterance  Speaker  \
0  1,"also I was the point person on my companyÂ’...        NaN      NaN
1  2,"You mustÂ’ve had your hands full.",The Inte...        NaN      NaN
2  3,"That I did. That I did.",Chandler,neutral,n...        NaN      NaN
3  4,"So letÂ’s talk a little bit about your duti...        NaN      NaN
4  5,"My duties?  All right.",Chandler,surprise,p...        NaN      NaN

   Emotion  Sentiment  Dialogue_ID  Utterance_ID  Season  Episode  StartTime  \
0      NaN        NaN          NaN           NaN     NaN      NaN        NaN
1      NaN        NaN          NaN           NaN     NaN      NaN        NaN
2      NaN        NaN          NaN           NaN     NaN      NaN        NaN
3      NaN        NaN          NaN           NaN     NaN      NaN        NaN
4      NaN        NaN          NaN           NaN     NaN      NaN        NaN

   EndTime
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN

AttributeError: Can only use .str accessor with string values!

In [22]:
import pandas as pd
df_train = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv', encoding='ISO-8859-1') # load the .csv file, specify the appropriate path
utt = df_train['Utterance'].tolist() # load the list of utterances
dia_id = df_train['Dialogue_ID'].tolist() # load the list of dialogue id's
utt_id = df_train['Utterance_ID'].tolist() # load the list of utterance id's

In [56]:
nRowsRead = 50 # specify 'None' if want to read whole file
# dev_sent_emo.csv may have more rows in reality, but we are only loading/previewing the first 1000 rows
df1 = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo_cleaned.csv', delimiter=',')
df1.dataframeName = 'dev_sent_emo.csv'
nRow, nCol = df1.shape
print(f'There are {nRow} rows and {nCol} columns')

There are 9988 rows and 11 columns

In [57]:
df1

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,1,also I was the point person on my companys tr...,Chandler,neutral,neutral,0,0,8,21,"00:16:16,059","00:16:21,731"
1,2,You mustve had your hands full.,The Interviewer,neutral,neutral,0,1,8,21,"00:16:21,940","00:16:23,442"
2,3,That I did. That I did.,Chandler,neutral,neutral,0,2,8,21,"00:16:23,442","00:16:26,389"
3,4,So lets talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3,8,21,"00:16:26,820","00:16:29,572"
4,5,My duties? All right.,Chandler,surprise,positive,0,4,8,21,"00:16:34,452","00:16:40,917"
...,...,...,...,...,...,...,...,...,...,...,...
9983,10474,You or me?,Chandler,neutral,neutral,1038,13,2,3,"00:00:48,173","00:00:50,799"
9984,10475,"I got it. Uh, Joey, women don't have Adam's ap...",Ross,neutral,neutral,1038,14,2,3,"00:00:51,009","00:00:53,594"
9985,10476,"You guys are messing with me, right?",Joey,surprise,positive,1038,15,2,3,"00:01:00,518","00:01:03,520"
9986,10477,Yeah.,All,neutral,neutral,1038,16,2,3,"00:01:05,398","00:01:07,274"
9987,10478,"That was a good one. For a second there, I was...",Joey,joy,positive,1038,17,2,3,"00:01:08,401","00:01:12,071"

In [50]:
df1.head(5)

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,1,also I was the point person on my companys tr...,Chandler,neutral,neutral,0,0,8,21,"00:16:16,059","00:16:21,731"
1,2,You mustve had your hands full.,The Interviewer,neutral,neutral,0,1,8,21,"00:16:21,940","00:16:23,442"
2,3,That I did. That I did.,Chandler,neutral,neutral,0,2,8,21,"00:16:23,442","00:16:26,389"
3,4,So lets talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3,8,21,"00:16:26,820","00:16:29,572"
4,5,My duties? All right.,Chandler,surprise,positive,0,4,8,21,"00:16:34,452","00:16:40,917"

In [55]:
import pandas as pd

# Charger le fichier CSV
df = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv', delimiter=',')

# Afficher le nom et la forme du DataFrame
df.dataframeName = 'dev_sent_emo.csv'
nRow, nCol = df.shape
print(f'There are {nRow} rows and {nCol} columns')

# Supprimer la ligne où Dialogue_ID = 125 et Utterance_ID = 3
df = df[~((df['Dialogue_ID'] == 125) & (df['Utterance_ID'] == 3))]

# Afficher la forme du DataFrame après suppression
nRow, nCol = df.shape
print(f'After deletion, there are {nRow} rows and {nCol} columns')

df.to_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo_cleaned.csv', index=False)

print("Le fichier a été enregistré avec succès.")

There are 9989 rows and 11 columns
After deletion, there are 9988 rows and 11 columns
Le fichier a été enregistré avec succès.

In [54]:
df

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID,Season,Episode,StartTime,EndTime
0,1,also I was the point person on my companys tr...,Chandler,neutral,neutral,0,0,8,21,"00:16:16,059","00:16:21,731"
1,2,You mustve had your hands full.,The Interviewer,neutral,neutral,0,1,8,21,"00:16:21,940","00:16:23,442"
2,3,That I did. That I did.,Chandler,neutral,neutral,0,2,8,21,"00:16:23,442","00:16:26,389"
3,4,So lets talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3,8,21,"00:16:26,820","00:16:29,572"
4,5,My duties? All right.,Chandler,surprise,positive,0,4,8,21,"00:16:34,452","00:16:40,917"
...,...,...,...,...,...,...,...,...,...,...,...
9984,10474,You or me?,Chandler,neutral,neutral,1038,13,2,3,"00:00:48,173","00:00:50,799"
9985,10475,"I got it. Uh, Joey, women don't have Adam's ap...",Ross,neutral,neutral,1038,14,2,3,"00:00:51,009","00:00:53,594"
9986,10476,"You guys are messing with me, right?",Joey,surprise,positive,1038,15,2,3,"00:01:00,518","00:01:03,520"
9987,10477,Yeah.,All,neutral,neutral,1038,16,2,3,"00:01:05,398","00:01:07,274"
9988,10478,"That was a good one. For a second there, I was...",Joey,joy,positive,1038,17,2,3,"00:01:08,401","00:01:12,071"

In [59]:
import pandas as pd

# Charger le fichier CSV
df1 = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo.csv', delimiter=',')

# Supprimer la ligne où Dialogue_ID = 125 et Utterance_ID = 3
df1 = df1[~((df1['Dialogue_ID'] == 125) & (df1['Utterance_ID'] == 3))]

# Supprimer les colonnes Season, Episode, StartTime, et EndTime
df1 = df1.drop(columns=['Season', 'Episode', 'StartTime', 'EndTime'])

# Enregistrer le DataFrame modifié dans un nouveau fichier CSV
df1.to_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo_cleaned.csv', index=False)

print("Le fichier a été enregistré avec succès.")

Le fichier a été enregistré avec succès.

In [60]:
df1

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID
0,1,also I was the point person on my companys tr...,Chandler,neutral,neutral,0,0
1,2,You mustve had your hands full.,The Interviewer,neutral,neutral,0,1
2,3,That I did. That I did.,Chandler,neutral,neutral,0,2
3,4,So lets talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3
4,5,My duties? All right.,Chandler,surprise,positive,0,4
...,...,...,...,...,...,...,...
9984,10474,You or me?,Chandler,neutral,neutral,1038,13
9985,10475,"I got it. Uh, Joey, women don't have Adam's ap...",Ross,neutral,neutral,1038,14
9986,10476,"You guys are messing with me, right?",Joey,surprise,positive,1038,15
9987,10477,Yeah.,All,neutral,neutral,1038,16
9988,10478,"That was a good one. For a second there, I was...",Joey,joy,positive,1038,17

In [61]:
df2 = pd.read_csv('E:/meldDatabase/MELD-RAW/MELD.Raw/train/train_sent_emo_cleaned.csv', delimiter=',')

In [62]:
df2

,Sr No.,Utterance,Speaker,Emotion,Sentiment,Dialogue_ID,Utterance_ID
0,1,also I was the point person on my companys tr...,Chandler,neutral,neutral,0,0
1,2,You mustve had your hands full.,The Interviewer,neutral,neutral,0,1
2,3,That I did. That I did.,Chandler,neutral,neutral,0,2
3,4,So lets talk a little bit about your duties.,The Interviewer,neutral,neutral,0,3
4,5,My duties? All right.,Chandler,surprise,positive,0,4
...,...,...,...,...,...,...,...
9983,10474,You or me?,Chandler,neutral,neutral,1038,13
9984,10475,"I got it. Uh, Joey, women don't have Adam's ap...",Ross,neutral,neutral,1038,14
9985,10476,"You guys are messing with me, right?",Joey,surprise,positive,1038,15
9986,10477,Yeah.,All,neutral,neutral,1038,16
9987,10478,"That was a good one. For a second there, I was...",Joey,joy,positive,1038,17